---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
    
      - name: Query ACI for Tenants
        cisco.aci.aci_rest:
          host: "{{ansible_host}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          method: get
          path: /api/node/mo/uni/tn-{{ tenant }}.json
        register: query_result #Register the response to query_result yes
      - name: Debug API Response
        debug:
          var: query_result